version: "3.9"

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    env_file:
      - mysql.env

  wordpress:
    image: wordpress:php8.0-fpm
    volumes:
      - ./wp:/var/www/html
    expose:
      - 9000
    env_file:
      - wordpress.env
    links:
      - mysql

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./wp:/var/www/html
    links:
      - wordpress
